app/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo


class RegisterForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired(), Email()])
    password = PasswordField(
        "Password", validators=[DataRequired(), EqualTo("password_confirm")]
    )
    password_confirm = PasswordField("Confirm Password", validators=[DataRequired()])
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    email = StringField("Email Address", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from werkzeug.urls import url_parse
from flask_login import login_user, current_user, logout_user, login_required

from app import bcrypt
from app.forms.auth import RegisterForm, LoginForm
from app.models.User import create_user, get_user_by_email

bp = Blueprint("auth", __name__)


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data

        if get_user_by_email(email):
            flash("A user already exists with that email address!")
            return render_template("auth/register.html", form=form), 400

        create_user(name, email, password)

        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("auth.login")

        flash("You have successfully registered. You can now login.")
        return redirect(next_page)

    return render_template("auth/register.html", form=form)


@bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    form = LoginForm()
    if form.validate_on_submit():
        user = get_user_by_email(form.email.data)

        if user is None or not bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            flash("Invalid email address or password")
            return render_template("auth/login.html", title="Sign In", form=form), 401

        login_user(user)
        session["user_name"] = user.name
        session["user_id"] = user.id
        session["is_admin"] = user.is_admin
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("main.dashboard")

        flash("You have been logged in", "success")
        return redirect(next_page)

    return render_template("auth/login.html", form=form)


@bp.route("/logout")
@login_required
def logout():
    if current_user.is_authenticated:
        logout_user()
        flash("You have been logged out")
    return redirect(url_for("auth.login"))

app/routes/main.py
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required

from app.models.Student import (
    get_mentor_students,
    get_mentor_active_students,
    get_mentor_sessions_between_dates,
)

bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    return render_template("index.html")


@bp.route("/dashboard")
@login_required
def dashboard():
    start = datetime.utcnow().replace(day=1, hour=0, minute=0, second=0)
    end = datetime.utcnow()

    total_students = get_mentor_students(current_user.id)
    active_students = get_mentor_active_students(current_user.id)
    month_sessions = get_mentor_sessions_between_dates(current_user.id, start, end)

    return render_template(
        "dashboard.html",
        total_students=total_students,
        active_students=active_students,
        month_sessions=month_sessions,
    )

app/routes/reports.py
from datetime import datetime
from math import floor
from decimal import Decimal

from flask import Blueprint, render_template
from flask_login import current_user, login_required

from app.models.Student import (
    get_mentor_sessions_between_dates,
    get_mentor_active_students_by_contact,
)

bp = Blueprint("reports", __name__)


@bp.route("/reports/sessions-report", methods=["GET"])
@login_required
def sessions_report():
    start = datetime.utcnow().replace(day=1, hour=0, minute=0, second=0)
    end = datetime.utcnow()

    sessions = get_mentor_sessions_between_dates(current_user.id, start, end)
    duration_mins = calculate_sessions_duration_min_mins(sessions)
    duration = format_duration_string(duration_mins)
    invoice_amount = Decimal(
        (duration_mins / 60) * (current_user.hourly_rate / 100)
    ).quantize(Decimal(10) ** -2)

    return render_template(
        "reports/sessions.html",
        sessions=sessions,
        duration=duration,
        invoice_amount=invoice_amount,
    )


@bp.route("/reports/student-activity-report", methods=["GET"])
@login_required
def student_activity_report():
    students = get_mentor_active_students_by_contact(current_user.id)

    return render_template("reports/activity_report.html", students=students)


def calculate_sessions_duration_min_mins(sessions):
    duration_mins = 0
    for session in sessions:
        duration_mins += session.duration

    return duration_mins


def format_duration_string(duration_mins):
    hours = floor(duration_mins / 60)
    mins = duration_mins % 60
    mins = mins if len(str(mins)) > 1 else f"0{mins}"

    return f"{hours} Hours and {mins} minutes"

app/routes/users.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash, session
from flask_login import login_required, current_user

from app.models.User import (
    get_user_by_id,
    change_user_password,
    update_user,
    get_all_users,
)
from app.forms.users import UserPasswordUpdateForm, UserProfileForm

bp = Blueprint("users", __name__)


@bp.route("/users", methods=["GET"])
@login_required
def list():
    if not session["is_admin"]:
        return abort(403)

    users = get_all_users()

    return render_template("users/list.html", users=users)


@bp.route("/users/<user_id>", methods=["GET"])
@login_required
def show(user_id):
    user = get_user_by_id(user_id)
    password_form = UserPasswordUpdateForm()
    profile_form = UserProfileForm()

    if not user:
        return abort(404)

    if current_user.id != user.id and not current_user.is_admin:
        return abort(403)

    return render_template(
        "users/show.html",
        user=user,
        password_form=password_form,
        profile_form=profile_form,
    )


@bp.route("/users/<user_id>/password", methods=["POST"])
@login_required
def change_password(user_id):
    form = UserPasswordUpdateForm()
    if form.validate_on_submit():
        change_user_password(user_id, form.password.data)

        flash("Password successfully updated", "success")
        return redirect(url_for("users.show", user_id=user_id))


@bp.route("/users/<user_id>/profile", methods=["POST"])
@login_required
def update_profile(user_id):
    form = UserProfileForm()
    if form.validate_on_submit():
        update_user(user_id, form.name.data, form.email.data, form.hourly_rate.data)

        flash("Profile data successfully updated", "success")
        return redirect(url_for("users.show", user_id=user_id))

app/templates/layouts/app.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MentorDashboard</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    {% block styles %}{% endblock %}
</head>

<body class="bg-gray-100 font-sans leading-normal tracking-normal">

<nav id="header" class="bg-gray-900 fixed w-full z-10 top-0 shadow">
    <div class="w-full container mx-auto flex flex-wrap items-center mt-0 pt-3 pb-3 md:pb-0">
        <div class="w-1/2 pl-2 md:pl-0">
            <a class="text-white text-base xl:text-xl no-underline hover:no-underline font-bold"
               href="{{ url_for('main.dashboard') }}">
                MentorDashboard
            </a>
        </div>
        <div class="w-1/2 pr-0">
            <div class="flex relative inline-block float-right">
                <div class="relative text-sm">
                    <button id="userButton" class="flex items-center focus:outline-none mr-3 text-white">
                        <span class="hidden md:inline-block">Hi, {{ session["user_name"] }} </span>
                        <svg class="pl-2 h-2 fill-current text-gray-100" version="1.1"
                             xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129"
                             enable-background="new 0 0 129 129">
                            <g>
                                <path
                                        d="m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z"/>
                            </g>
                        </svg>
                    </button>
                    <div id="userMenu"
                         class="bg-white rounded shadow-md mt-2 absolute mt-12 top-0 right-0 min-w-full overflow-auto z-30 invisible">
                        <ul class="list-reset">
                            <li>
                                <a href="{{ url_for('users.show', user_id=session['user_id']) }}"
                                   class="px-4 py-2 block text-gray-900 hover:bg-gray-400 no-underline hover:no-underline">
                                    My account
                                </a>
                            </li>
                            <li>
                                <hr class="border-t mx-2 border-gray-400">
                            </li>
                            <li>
                                <a href="{{ url_for('auth.logout') }}"
                                   class="px-4 py-2 block text-gray-900 hover:bg-gray-400 no-underline hover:no-underline">Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="block lg:hidden pr-4">
                    <button id="nav-toggle"
                            class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-white hover:border-teal-500 appearance-none focus:outline-none">
                        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <title>Menu</title>
                            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-gray-900 z-20"
             id="nav-content">
            <ul class="list-reset lg:flex flex-1 items-center px-4 md:px-0">
                <li class="mr-6 my-2 md:my-0">
                    <a href="{{ url_for('main.dashboard') }}"
                       class="block py-1 md:py-3 pl-1 align-middle text-gray-500 no-underline hover:text-white border-b-4 border-white hover:border-indigo-600">
                        <span class="pb-1 md:pb-0 text-sm">Dashboard</span>
                    </a>
                </li>
                <li class="mr-6 my-2 md:my-0">
                    <a href="{{ url_for('students.index') }}"
                       class="block py-1 md:py-3 pl-1 align-middle text-gray-500 no-underline hover:text-white border-b-4 border-white hover:border-indigo-600">
                        <span class="pb-1 md:pb-0 text-sm">Students</span>
                    </a>
                </li>
                <li class="mr-6 my-2 md:my-0">
                    <a href="{{ url_for('reports.sessions_report') }}"
                       class="block py-1 md:py-3 pl-1 align-middle text-gray-500 no-underline hover:text-white border-b-4 border-white hover:border-indigo-600">
                        <span class="pb-1 md:pb-0 text-sm">Sessions Report</span>
                    </a>
                </li>
                <li class="mr-6 my-2 md:my-0">
                    <a href="{{ url_for('reports.student_activity_report') }}"
                       class="block py-1 md:py-3 pl-1 align-middle text-gray-500 no-underline hover:text-white border-b-4 border-white hover:border-indigo-600">
                        <span class="pb-1 md:pb-0 text-sm">Student Activity Report</span>
                    </a>
                </li>
                {% if session["is_admin"] == True %}
                    <li class="mr-6 my-2 md:my-0">
                        <a href="{{ url_for('users.list') }}"
                           class="block py-1 md:py-3 pl-1 align-middle text-gray-500 no-underline hover:text-white border-b-4 border-white hover:border-indigo-600">
                            <span class="pb-1 md:pb-0 text-sm">Users</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container w-full mx-auto pt-16">
    <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">
        {% include "partials/_messages.html" %}
        {% block app_content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.0/dist/alpine.min.js" defer></script>
<script>
    /*Toggle dropdown list*/
    /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/

    var userMenuDiv = document.getElementById("userMenu");
    var userMenu = document.getElementById("userButton");

    var navMenuDiv = document.getElementById("nav-content");
    var navMenu = document.getElementById("nav-toggle");

    document.onclick = check;

    function check(e) {
        var target = (e && e.target) || (event && event.srcElement);

        //User Menu
        if (!checkParent(target, userMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, userMenu)) {
                // click on the link
                if (userMenuDiv.classList.contains("invisible")) {
                    userMenuDiv.classList.remove("invisible");
                } else {
                    userMenuDiv.classList.add("invisible");
                }
            } else {
                // click both outside link and outside menu, hide menu
                userMenuDiv.classList.add("invisible");
            }
        }

        //Nav Menu
        if (!checkParent(target, navMenuDiv)) {
            // click NOT on the menu
            if (checkParent(target, navMenu)) {
                // click on the link
                if (navMenuDiv.classList.contains("hidden")) {
                    navMenuDiv.classList.remove("hidden");
                } else {
                    navMenuDiv.classList.add("hidden");
                }
            } else {
                // click both outside link and outside menu, hide menu
                navMenuDiv.classList.add("hidden");
            }
        }

    }

    function checkParent(t, elm) {
        while (t.parentNode) {
            if (t == elm) {
                return true;
            }
            t = t.parentNode;
        }
        return false;
    }
</script>
{% block js %}{% endblock %}
<noscript><img src="https://shynet.msrr.xyz/ingress/4c14aa9e-6633-47e8-9715-125c6991d415/pixel.gif"></noscript>
<script src="https://shynet.msrr.xyz/ingress/4c14aa9e-6633-47e8-9715-125c6991d415/script.js"></script>
</body>
</html>

app/templates/layouts/auth.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MentorDashboard</title>

    <!-- Styles -->
    <link href="{{ url_for('static', filename='css/app.css') }}" rel="stylesheet">
</head>
<body class="bg-gray-100 h-screen antialiased leading-none">
<div id="app">
    <nav class="bg-gray-900 shadow mb-8 py-6">
        <div class="container mx-auto px-6 md:px-0">
            <div class="flex items-center justify-center">
                <div class="mr-6">
                    <a href="{{ url_for('main.index') }}" class="text-lg font-semibold text-gray-100 no-underline">
                        MentorDashboard
                    </a>
                </div>
                <div class="flex-1 text-right">

                </div>
            </div>
        </div>
    </nav>

    {% block app_content %}{% endblock %}
</div>
<noscript><img src="https://shynet.msrr.xyz/ingress/4c14aa9e-6633-47e8-9715-125c6991d415/pixel.gif"></noscript>
<script src="https://shynet.msrr.xyz/ingress/4c14aa9e-6633-47e8-9715-125c6991d415/script.js"></script>
</body>
</html>