app/models/User.py
from datetime import datetime
from flask_login import UserMixin
from flask import current_app

from app import db, login, bcrypt


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    email = db.Column(db.String(255), index=True, unique=True)
    password = db.Column(db.String(255))
    hourly_rate = db.Column(db.Integer, default=0)
    is_admin = db.Column(db.Boolean, default=False, nullable=False)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, current_app.config["BCRYPT_LOG_ROUNDS"]
        ).decode()


def create_user(name, email, password):
    user = User(name, email, password)
    db.session.add(user)
    db.session.commit()

    return user


def get_user_by_email(email):
    return User.query.filter_by(email=email).first()


def get_user_by_id(user_id):
    return User.query.get(user_id)


def change_user_password(user_id, password):
    user = get_user_by_id(user_id)
    user.password = bcrypt.generate_password_hash(
        password, current_app.config["BCRYPT_LOG_ROUNDS"]
    ).decode()

    db.session.commit()

    return True


def update_user(user_id, name, email, hourly_rate):
    user = get_user_by_id(user_id)
    user.name = name
    user.email = email
    user.hourly_rate = hourly_rate

    db.session.commit()

    return True


def get_all_users():
    return User.query.all()


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/forms/users.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    PasswordField,
    IntegerField,
)
from wtforms.validators import DataRequired, Email, EqualTo


class UserProfileForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    hourly_rate = IntegerField("Hourly Rate", validators=[DataRequired()])
    submit = SubmitField("Update Profile")


class UserPasswordUpdateForm(FlaskForm):
    password = PasswordField(
        "Password", validators=[DataRequired(), EqualTo("password_confirm")]
    )
    password_confirm = PasswordField("Confirm Password", validators=[DataRequired()])
    submit = SubmitField("Change Password")

app/routes/users.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash, session
from flask_login import login_required, current_user

from app.models.User import (
    get_user_by_id,
    change_user_password,
    update_user,
    get_all_users,
)
from app.forms.users import UserPasswordUpdateForm, UserProfileForm

bp = Blueprint("users", __name__)


@bp.route("/users", methods=["GET"])
@login_required
def list():
    if not session["is_admin"]:
        return abort(403)

    users = get_all_users()

    return render_template("users/list.html", users=users)


@bp.route("/users/<user_id>", methods=["GET"])
@login_required
def show(user_id):
    user = get_user_by_id(user_id)
    password_form = UserPasswordUpdateForm()
    profile_form = UserProfileForm()

    if not user:
        return abort(404)

    if current_user.id != user.id and not current_user.is_admin:
        return abort(403)

    return render_template(
        "users/show.html",
        user=user,
        password_form=password_form,
        profile_form=profile_form,
    )


@bp.route("/users/<user_id>/password", methods=["POST"])
@login_required
def change_password(user_id):
    form = UserPasswordUpdateForm()
    if form.validate_on_submit():
        change_user_password(user_id, form.password.data)

        flash("Password successfully updated", "success")
        return redirect(url_for("users.show", user_id=user_id))


@bp.route("/users/<user_id>/profile", methods=["POST"])
@login_required
def update_profile(user_id):
    form = UserProfileForm()
    if form.validate_on_submit():
        update_user(user_id, form.name.data, form.email.data, form.hourly_rate.data)

        flash("Profile data successfully updated", "success")
        return redirect(url_for("users.show", user_id=user_id))

app/templates/users/list.html
{% extends "layouts/app.html" %}

{% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block app_content %}
    <div class="bg-indigo-600 p-2 shadow text-xl text-white flex justify-between">
        <h3 class="font-bold pl-2 inline">User Management</h3>
    </div>
    <section>
        <div id='users' class="p-8 mt-6 lg:mt-0 rounded shadow bg-white">
            <table id="usersTable" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                <thead>
                <tr>
                    <th class="px-4 py-2">Name</th>
                    <th class="px-4 py-2">Email</th>
                    <th class="px-4 py-2">Admin</th>
                    <th class="px-4 py-2">Registered</th>
                    <th class="px-4 py-2">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td class="border px-4 py-2">
                            {{ user.name }}
                        </td>
                        <td class="border px-4 py-2">
                            {{ user.email }}
                        </td>
                        <td class="border px-4 py-2">
                            {{ "Yes" if user.is_admin == True else "no" }}
                        </td>
                        <td class="border px-4 py-2">
                            {{ user.created_at }}
                        </td>
                        <td class="border px-4 py-2">
                            <a class="bg-green-500 text-white font-bold py-2 px-4 focus:outline-none focus:shadow-outline mr-1"
                               href="{{ url_for('users.show', user_id=user.id) }}">
                                View
                            </a>
                            {% if session["user_id"] != user.id %}
                                <a class="bg-orange-500 text-white font-bold py-2 px-4 focus:outline-none focus:shadow-outline"
                                   href="#">
                                    Impersonate
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
    <script>
        const usersTable = new simpleDatatables.DataTable("#usersTable", {
            searchable: true,
            fixedHeight: true,
            perPage: 15,
        });
    </script>
{% endblock %}

app/templates/users/show.html
{% extends 'layouts/app.html' %}

{% block app_content %}
    <div x-data="modals()">
        <div class="bg-indigo-600 p-2 shadow text-xl text-white flex justify-between">
            <h3 class="font-bold pl-2 inline">User Profile</h3>
            <div>
                <button class="font-bold pr-2" @click="showChangePasswordModal = true">Change Password</button>
                <button class="font-bold pr-2" @click="showEditProfileModal = true">Edit Profile</button>
            </div>
        </div>
        <section>
            <div class="p-8 py-4 shadow bg-white">
                <span class="font-bold">Name:</span> {{ user.name }} <br/>
                <span class="font-bold">Email Address:</span> {{ user.email }}<br/>
                <span class="font-bold">Hourly Rate:</span> &euro;{{ user.hourly_rate / 100 }}
            </div>
        </section>

        <!-- Change Password Modal -->
        <div class="absolute top-0 left-0 w-full h-full flex items-center justify-center"
             style="background-color: rgba(0,0,0,.5);" x-show="showChangePasswordModal">
            <div class="text-left bg-white h-auto w-1/3 shadow-xl p-4 rounded mx-2 md:mx-0"
                 @click.away="showChangePasswordModal = false">
                <h2 class="text-2xl">Change Password</h2>
                <form class="px-0 pt-6 pb-2 mb-4"
                      action="{{ url_for('users.change_password', user_id=user.id) }}" method="POST">
                    {{ password_form.hidden_tag() }}
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2" for="note">
                            Password
                        </label>
                        <input
                            class="tracking-wide shadow appearance-none border w-full py-2 px-1 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                            id="password" type="password" name="password" placeholder="Password" required />
                    </div>
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2" for="note">
                            Confirm Password
                        </label>
                        <input
                            class="tracking-wide shadow appearance-none border w-full py-2 px-1 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                            id="password_confirm" type="password" name="password_confirm" placeholder="Password Confirmation" required />
                    </div>
                    <div class="flex justify-center mt-4">
                        <button
                            class="bg-indigo-600 text-white px-4 py-2 rounded no-outline focus:shadow-outline select-none"
                            type="submit">
                            Change Password
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Edit Profile Modal -->
        <div class="absolute top-0 left-0 w-full h-full flex items-center justify-center"
             style="background-color: rgba(0,0,0,.5);" x-show="showEditProfileModal">
            <div class="text-left bg-white h-auto w-1/3 shadow-xl p-4 rounded mx-2 md:mx-0"
                 @click.away="showEditProfileModal = false">
                <h2 class="text-2xl">Edit Profile</h2>
                <form class="px-0 pt-6 pb-2 mb-4"
                      action="{{ url_for('users.update_profile', user_id=user.id) }}" method="POST">
                    {{ profile_form.hidden_tag() }}
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2" for="name">
                            Name
                        </label>
                        <input
                            class="tracking-wide shadow appearance-none border w-full py-2 px-1 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                            id="name" type="text" name="name" placeholder="Name" value="{{ user.name }}" required />
                    </div>
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                            Email Address
                        </label>
                        <input
                            class="tracking-wide shadow appearance-none border w-full py-2 px-1 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                            id="email" type="email" name="email" placeholder="Email Address" value="{{ user.email }}" required />
                    </div>
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2" for="hourly_rate">
                            Hourly Rate (in cents)
                        </label>
                        <input
                            class="tracking-wide shadow appearance-none border w-full py-2 px-1 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                            id="hourly_rate" type="number" name="hourly_rate" placeholder="Hourly Rate (in cents)" value="{{ user.hourly_rate }}" required />
                    </div>
                    <div class="flex justify-center mt-4">
                        <button
                            class="bg-indigo-600 text-white px-4 py-2 rounded no-outline focus:shadow-outline select-none"
                            type="submit">
                            Update Profile
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
        function modals() {
            return {
                showChangePasswordModal: false,
                showEditProfileModal: false,
            }
        }
    </script>
{% endblock %}