app/models/Student.py
from datetime import datetime

from app import db


class Student(db.Model):
    __tablename__ = "students"

    id = db.Column(db.Integer, primary_key=True)
    mentor_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    name = db.Column(db.String(255))
    email = db.Column(db.String(255), index=True)
    course = db.Column(db.String(20))
    stage = db.Column(db.String(20))
    active = db.Column(db.Boolean, default=True, nullable=False)
    last_contact = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    notes = db.relationship("StudentNote", backref="student", lazy=True)
    sessions = db.relationship("StudentSession", backref="student", lazy=True)

    def __init__(self, name, email, course, stage, mentor_id):
        self.name = name
        self.email = email
        self.course = course
        self.stage = stage
        self.mentor_id = mentor_id

    @property
    def serialize(self):
        return {"id": self.id, "name": self.name, "email": self.email}


class StudentNote(db.Model):
    __tablename__ = "student_notes"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("students.id"), nullable=False)
    note = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    def __init__(self, student_id, note):
        self.student_id = student_id
        self.note = note


class StudentSession(db.Model):
    __tablename__ = "student_sessions"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("students.id"), nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    duration = db.Column(db.Integer, nullable=False)
    session_type = db.Column(db.String(32), nullable=False)
    project = db.Column(db.String(32), nullable=False)
    summary = db.Column(db.Text, nullable=False)
    progress = db.Column(db.String(32), nullable=False)
    followup = db.Column(db.String(32), nullable=True)
    personal_notes = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    def __init__(
        self,
        student_id,
        date,
        duration,
        session_type,
        project,
        summary,
        progress,
        followup,
        personal_notes,
    ):
        self.student_id = student_id
        self.date = date
        self.duration = duration
        self.session_type = session_type
        self.project = project
        self.summary = summary
        self.progress = progress
        self.followup = followup
        self.personal_notes = personal_notes

    @property
    def serialize(self):
        return {
            "id": self.id,
            "student": self.student.serialize,
            "date": self.date.strftime("%Y-%m-%d %H:%M:%S"),
            "duration": self.duration,
            "session_type": self.session_type,
            "project": self.project,
            "summary": self.summary,
            "progress": self.progress,
            "followup": str(self.followup),
            "personal_notes": str(self.personal_notes),
        }


def create_student(name, email, course, stage, mentor_id):
    student = Student(name, email, course, stage, mentor_id)
    db.session.add(student)
    db.session.commit()

    return student


def get_mentor_students(mentor_id, active_only=False):
    if active_only:
        return (
            Student.query.filter_by(mentor_id=mentor_id)
            .filter_by(active=1)
            .order_by(Student.name.asc())
            .all()
        )

    return (
        Student.query.filter_by(mentor_id=mentor_id).order_by(Student.name.asc()).all()
    )


def get_mentor_active_students_by_contact(mentor_id):
    return (
        Student.query.filter_by(mentor_id=mentor_id)
        .filter_by(active=1)
        .order_by(Student.last_contact.asc())
    )


def get_mentor_active_students(mentor_id):
    return (
        Student.query.filter_by(mentor_id=mentor_id, active=1)
        .order_by(Student.name.asc())
        .all()
    )


def get_student_by_id(student_id):
    return Student.query.get(student_id)


def update_student(student_id, name, email, course, stage, active, mentor_id):
    student = get_student_by_id(student_id)

    if student.mentor_id is not mentor_id:
        return False

    student.name = name
    student.email = email
    student.course = course
    student.stage = stage
    student.active = active

    db.session.commit()
    return True


def add_student_note(student_id, note):
    note = StudentNote(student_id, note)
    db.session.add(note)
    db.session.commit()

    return note


def update_contact_date(student_id):
    student = get_student_by_id(student_id)
    student.last_contact = datetime.utcnow()
    db.session.commit()

    return student


def create_student_session(
    student_id,
    date,
    duration,
    session_type,
    project,
    summary,
    progress,
    followup,
    personal_notes,
):
    session = StudentSession(
        student_id,
        date,
        duration,
        session_type,
        project,
        summary,
        progress,
        followup,
        personal_notes,
    )
    db.session.add(session)
    db.session.commit()

    update_contact_date(student_id)

    return session


def get_session_by_id(session_id):
    return StudentSession.query.get(session_id)


def update_student_session(
    student_id,
    session_id,
    date,
    duration,
    session_type,
    project,
    summary,
    progress,
    followup,
    personal_notes,
):
    session = get_session_by_id(session_id)

    session.date = date
    session.duration = duration
    session.session_type = session_type
    session.project = project
    session.summary = summary
    session.progress = progress
    session.followup = followup
    session.personal_notes = personal_notes

    db.session.commit()

    update_contact_date(student_id)

    return session


def get_mentor_sessions_between_dates(mentor_id, start, end):
    students = get_mentor_students(mentor_id)
    student_ids = []

    for student in students:
        student_ids.append(student.id)

    return (
        StudentSession.query.filter(StudentSession.date > start)
        .filter(StudentSession.date <= end)
        .filter(StudentSession.student_id.in_(student_ids))
        .all()
    )

app/forms/students.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    BooleanField,
    TextAreaField,
    SelectField,
    DateTimeField,
    IntegerField,
)
from wtforms.validators import DataRequired, Email, Optional


class AddStudentForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired(), Email()])
    course = StringField("Course", validators=[DataRequired()])
    stage = StringField("Stage", validators=[DataRequired()])
    submit = SubmitField("Add Student")


class EditStudentForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired(), Email()])
    course = StringField("Course", validators=[DataRequired()])
    stage = StringField("Stage", validators=[DataRequired()])
    active = SelectField("Active", validators=[DataRequired()], choices=["1", "0"])
    submit = SubmitField("Update Student")


class AddStudentNoteForm(FlaskForm):
    note = TextAreaField("Note", validators=[DataRequired()])
    update_contact_date = SelectField(
        "Update Contact Date", validators=[DataRequired()], choices=["yes", "no"]
    )


class AddStudentSessionForm(FlaskForm):
    date = DateTimeField("Date", validators=[DataRequired()])
    duration = IntegerField("Duration", validators=[DataRequired()])
    session_type = SelectField(
        "Session Type",
        validators=[DataRequired()],
        choices=["intro", "inception", "middle", "end", "prep", "no-show", "no-show-valid", "other"],
    )
    project = SelectField(
        "Project",
        validators=[DataRequired()],
        choices=["intro", "UCFD", "IFD", "DCD", "FSFwD", "PP1", "PP2", "PP3", "PP4", "PP5"],
    )
    summary = TextAreaField("Summary", validators=[DataRequired()])
    progress = SelectField(
        "Student Progress",
        validators=[DataRequired()],
        choices=["poor", "average", "excellent"],
    )
    followup = SelectField(
        "Would you like a follow up on this session?",
        validators=[DataRequired()],
        choices=["No", "Yes"],
    )
    personal_notes = TextAreaField("Personal Notes")
    send_feedback = SelectField(
        "Send Feedback", choices=["yes", "no"], validators=[Optional()]
    )

app/routes/students.py
from math import floor

import htmlentities
from flask import Blueprint, flash, redirect, render_template, url_for, abort, session
from flask_login import login_required, current_user

from app.forms.students import (
    AddStudentForm,
    EditStudentForm,
    AddStudentNoteForm,
    AddStudentSessionForm,
)
from app.models.Student import (
    create_student,
    get_mentor_students,
    update_student,
    get_student_by_id,
    add_student_note,
    update_contact_date,
    create_student_session,
    update_student_session,
    get_session_by_id,
)

bp = Blueprint("students", __name__)


@bp.route("/students", methods=["GET"])
@login_required
def index():
    students = get_mentor_students(current_user.id)
    return render_template("students/index.html", students=students)


@bp.route("/students/active", methods=["GET"])
@login_required
def active_students():
    students = get_mentor_students(current_user.id, active_only=True)
    return render_template("students/index.html", students=students)


@bp.route("/students/new", methods=["POST", "GET"])
@login_required
def new():
    form = AddStudentForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        course = form.course.data
        stage = form.course.data

        create_student(name, email, course, stage, current_user.id)

        flash("New student saved")
        return redirect(url_for("students.index"))

    return render_template("students/create.html", form=form)


@bp.route("/students/<student_id>")
@login_required
def view(student_id):
    student = get_student_by_id(student_id)
    add_student_note_form = AddStudentNoteForm()

    if not student:
        return abort(404)

    if current_user.id is not student.mentor_id:
        return abort(404)

    return render_template(
        "students/view.html",
        student=student,
        add_student_note_form=add_student_note_form,
    )


@bp.route("/students/<student_id>/edit", methods=["POST", "GET"])
@login_required
def edit(student_id):
    form = EditStudentForm()
    student = get_student_by_id(student_id)
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        course = form.course.data
        stage = form.stage.data
        active = True if form.active.data == "1" else False

        if not update_student(
            student.id, name, email, course, stage, active, current_user.id
        ):
            return redirect(url_for("students.index")), 403

        flash("Student Successfully Updated")
        return redirect(url_for("students.index"))

    return render_template("students/edit.html", form=form, student=student)


@bp.route("/students/<student_id>/notes", methods=["POST"])
@login_required
def add_note(student_id):
    form = AddStudentNoteForm()
    student = get_student_by_id(student_id)
    if form.validate_on_submit():
        note = form.note.data

        add_student_note(student.id, note)

        if form.update_contact_date.data == "yes":
            update_contact_date(student_id)

        flash("Note successfully saved", "success")
        return redirect(url_for("students.view", student_id=student.id))

    flash(
        "There was a problem adding this note, make sure you actually add a note",
        "error",
    )
    return render_template(
        "students/view.html", student=student, add_student_note_form=form
    )


@bp.route("/students/<student_id>/sessions", methods=["POST", "GET"])
@login_required
def add_session(student_id):
    form = AddStudentSessionForm()
    student = get_student_by_id(student_id)
    if form.validate_on_submit():
        date = form.date.data
        duration = form.duration.data + 4
        session_type = form.session_type.data
        project = form.project.data
        summary = form.summary.data
        progress = form.progress.data
        followup = form.followup.data
        personal_notes = form.personal_notes.data

        student_session = create_student_session(
            student_id,
            date,
            duration,
            session_type,
            project,
            summary,
            progress,
            followup,
            personal_notes,
        )

        if form.send_feedback.data == "yes":
            session["feedback_url"] = generate_feedback_url(
                student, student_session, current_user
            )

        flash("Session successfully saved", "success")
        return redirect(url_for("students.view", student_id=student.id))

    return render_template("students/sessions/create.html", student=student, form=form)


@bp.route("/students/<student_id>/sessions/<session_id>/edit", methods=["GET", "POST"])
@login_required
def update_session(student_id, session_id):
    form = AddStudentSessionForm()
    student = get_student_by_id(student_id)
    session = get_session_by_id(session_id)
    if form.validate_on_submit():
        date = form.date.data
        duration = form.duration.data
        session_type = form.session_type.data
        project = form.project.data
        summary = form.summary.data
        progress = form.progress.data
        followup = form.followup.data
        personal_notes = form.personal_notes.data

        update_student_session(
            student_id,
            session_id,
            date,
            duration,
            session_type,
            project,
            summary,
            progress,
            followup,
            personal_notes,
        )

        flash("Session successfully updated", "success")
        return redirect(url_for("students.view", student_id=student_id))

    return render_template(
        "students/sessions/edit.html", student=student, form=form, session=session
    )


def generate_feedback_url(student, student_session, mentor):
    """
    Generates URL to autofill CI session feedback
    :param student:
    :param student_session:
    :param mentor:
    :return: string
    """
    types = {
        "select": "Please Select",
        "intro": "Intro",
        "inception": "Project inception",
        "middle": "Middle of project",
        "end": "End of project",
        "prep": "Interview preparation and career advice",
        "no-show-valid": "Postponed (Valid Reason)",
        "no-show": "**No-show**",
        "other": "Other",
    }

    projects = {
        "intro": "Intro/Interview",
        "UCFD": "User Centric Front End Development (MS1)",
        "IFD": "Interactive Front End Development (MS2)",
        "DCD": "Data Centric Development (MS3)",
        "FSFwD": "Full Stack Frameworks with Django (MS4)",
        "PP1": "HTML/CSS Essentials (PP1)",
        "PP2": "JavaScript Essentials (PP2)",
        "PP3": "Python Essentials (PP3)",
        "PP4": "Full Stack Toolkit (PP4)",
        "PP5": "eCommerce (PP5)",
    }

    progress = {
        "poor": "I'm worried about this student's progress.",
        "average": "Average - The student is moving at an acceptable pace.",
        "excellent": "Excellent - It's going great.",
    }
    followup = {
        "Yes": "Yes",
        "No": "No",
    }
    firstsubmission = {
        "Yes": "First Time Submission",
        "No": "Project Resubmission"
    }

    hours = floor(student_session.duration / 60)
    mins = str(student_session.duration  % 60)
    mins = mins if len(mins) > 1 else f"0{mins}"
    duration = f"0{hours}:{mins}:00"

    feedbackurl = "https://docs.google.com/forms/d/e/1FAIpQLSfUCSyObKZDjjtAhIgc8r5FrA4VSUflq1dMK6QyYMv33LeEDQ/viewform?c=0&w=1"
    feedbackurl += f"&emailAddress={htmlentities.encode(mentor.email)}"
    feedbackurl += f"&entry.1191000917={htmlentities.encode(student_session.date.strftime('%Y-%m-%d'))}"
    feedbackurl += f"&entry.1269347964={htmlentities.encode(student.email)}"
    feedbackurl += (
        f"&entry.1521715512={htmlentities.encode(types[student_session.session_type])}"
    )
    feedbackurl += (
        f"&entry.478142644={htmlentities.encode(projects[student_session.project])}"
    )
    feedbackurl += f"&entry.775489883={htmlentities.encode(duration)}"
    feedbackurl += (
        f"&entry.2010663110={htmlentities.encode(progress[student_session.progress])}"
    )
    feedbackurl += f"&entry.1882714143={htmlentities.encode(student_session.summary)}"
    feedbackurl += f"&entry.1360996801={htmlentities.encode(student_session.followup)}"
    feedbackurl += "&entry.1121396892=First Time Submission"
    feedbackurl += "&emailReceipt=true"

    return feedbackurl.replace("\r", " ").replace("\n", "")

app/templates/students/create.html
{% extends 'layouts/app.html' %}

{% block app_content %}
    <div class="bg-indigo-600 p-2 shadow text-xl text-white flex justify-between">
        <h3 class="font-bold pl-2 inline">Add New Student</h3>
    </div>
    <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST" action="{{ url_for('students.new') }}">
        {{ form.hidden_tag() }}
        <div class="mb-4">
            <label class="block text-grey-darker text-sm font-bold mb-2" for="name">
                Name
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                   id="name" name="name" type="text" placeholder="Name">
            {% for error in form.name.errors %}
                {{ error }}
            {% endfor %}
        </div>

        <div class="mb-4">
            <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                Email Address
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                   id="email" name="email" type="email" placeholder="student@domain.com">
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
        </div>

        <div class="mb-4">
            <label class="block text-grey-darker text-sm font-bold mb-2" for="course">
                Course Code
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                   id="course" name="course" type="text" placeholder="Course Code">
            {% for error in form.course.errors %}
                {{ error }}
            {% endfor %}
        </div>

        <div class="mb-4">
            <label class="block text-grey-darker text-sm font-bold mb-2" for="stage">
                Course Stage
            </label>
            <select class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                    id="stage" name="stage">
                <option value="unknown">Unknown</option>
                <option value="UCFD">User Centric Frontend Development</option>
                <option value="IFD">Interactive Frontend Development</option>
                <option value="DCD">Data Centric Development</option>
                <option value="FSFwD">Full Stack Frameworks with Django</option>
                <option value="completed">Completed</option>
            </select>
            {% for error in form.stage.errors %}
                {{ error }}
            {% endfor %}
        </div>

        <div class="flex items-center justify-between">
            <input class="bg-indigo-600 hover:bg-indigo-900 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                   type="submit" value="Add Student"/>

        </div>
    </form>
{% endblock %}

app/templates/students/view.html
{% extends 'layouts/app.html' %}

{% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block app_content %}
    <div x-data="modals()">
        <div class="bg-indigo-600 p-2 shadow text-xl text-white flex justify-between">
            <h3 class="font-bold pl-2 inline">Student Management</h3>
            <div>
                <button class="font-bold pr-2" @click="showNewNoteModal = true">Add Note</button>
                <a href="{{ url_for('students.add_session', student_id=student.id) }}">
                    <button class="font-bold pr-2">Record Session</button>
                </a>
                <a href="{{ url_for('students.edit', student_id=student.id) }}">
                    <button class="font-bold pr-2">Edit Student</button>
                </a>
            </div>
        </div>
        <section>
            <div id='student' class="p-8 py-4 shadow bg-white">
                Student Name: {{ student.name }} <br/>
                Email Address: {{ student.email }}<br/>
                Course: {{ student.course }}<br/>
                Stage: {{ student.stage }}<br/>
                Last Contact: {{ student.last_contact }}<br/>
                Status: {{ 'Active' if student.active == 1 else 'InActive' }}<br/>
            </div>
        </section>

        <section>
            <div class="px-8 py-4 shadow bg-white">
                <h4 class="text-2xl">Student Sessions</h4>
                <table id="sessions" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                    <thead>
                    <tr>
                        <th class="px-4 py-2">Date</th>
                        <th class="px-4 py-2">Duration</th>
                        <th class="px-4 py-2">Project</th>
                        <th class="px-4 py-2">Session Type</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for session in student.sessions %}
                        <tr class="clickable" @click="showSessionDetails({{ session.serialize }})">
                            <td class="border px-4 py-2">
                                {{ session.date }}
                            </td>
                            <td class="border px-4 py-2">
                                {{ session.duration }}
                            </td>
                            <td class="border px-4 py-2">
                                {{ session.project }}
                            </td>
                            <td class="border px-4 py-2">
                                {{ session.session_type }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>

        <section>
            <div class="px-8 py-4 shadow bg-white">
                <h4 class="text-2xl">Notes</h4>
                <table id="notes" class="min-w-full py-1">
                    <thead>
                    <tr>
                        <th class="px-4 py-2">Date</th>
                        <th class="px-4 py-2">Note</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for note in student.notes %}
                        <tr>
                            <td class="border px-4 py-2">{{ note.created_at }}</td>
                            <td class="border px-4 py-2">{{ note.note }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>


        <!-- New Note Modal -->
        <div class="absolute top-0 left-0 w-full h-full flex items-center justify-center"
             style="background-color: rgba(0,0,0,.5);" x-show="showNewNoteModal">
            <div class="text-left bg-white h-auto w-1/3 shadow-xl p-4 rounded mx-2 md:mx-0"
                 @click.away="showNewNoteModal = false">
                <h2 class="text-2xl">Add Student Note</h2>
                <form class="px-0 pt-6 pb-2 mb-4"
                      action="{{ url_for('students.add_note', student_id=student.id) }}" method="POST">
                    {{ add_student_note_form.hidden_tag() }}
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2 hidden" for="note">
                            Note
                        </label>
                        <textarea
                                class="autoexpand tracking-wide shadow appearance-none border w-full py-2 px-1 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                                id="note" type="text" name="note" placeholder="Note..."
                                rows="4" required></textarea>
                    </div>
                    <div class="mb-4">
                        <label class="block text-grey-darker text-sm font-bold mb-2" for="send_welcome_email">
                            Update Contact Date
                        </label>
                        <select
                                class="shadow appearance-none border w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                                id="update_contact_date" name="update_contact_date">
                            <option value="yes">Yes</option>
                            <option value="no" selected>No</option>
                        </select>
                    </div>
                    <div class="flex justify-center mt-4">
                        <button
                                class="bg-indigo-600 text-white px-4 py-2 rounded no-outline focus:shadow-outline select-none"
                                type="submit">
                            Save Note
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Session details modal -->
        <div class="absolute top-0 left-0 w-full h-full flex items-center justify-center"
             style="background-color: rgba(0,0,0,.5);" x-show="showSessionDetailsModal">
            <div class="text-left bg-white h-auto w-1/3 shadow-xl p-4 rounded mx-2 md:mx-0"
                 @click.away="showSessionDetailsModal = false">
                <div class="modal-content py-4 text-left px-6">
                    <div class="flex justify-between items-center pb-3">
                        <p class="text-2xl font-bold">Session Report</p>
                    </div>

                    <!--Body-->
                    <p><strong>Date:</strong> <span x-text="session.date"></span></p>
                    <p><strong>Duration (mins):</strong> <span x-text="session.duration"></span></p>
                    <p><strong>Type:</strong> <span x-text="session.session_type"></span></p>
                    <p><strong>Project:</strong> <span x-text="session.project"></span></p>
                    <p><strong>Progress:</strong> <span x-text="session.progress"></span></p>
                    <p><strong>Summary:</strong> <span x-text="session.summary"></span></p>
                    <p><strong>Concerns:</strong> <span x-text="session.concerns"></span></p>
                    <p><strong>Notes:</strong> <span x-text="session.personal_notes"></span></p>

                    <!--Footer-->
                    <div class="flex justify-end pt-2">
                        <a class="px-4 mr-2 bg-red-500 p-3 rounded-lg text-white hover:bg-red-400 clickable edit-link"
                           @click="editSession()">
                            Edit
                        </a>
                        <button class="px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400"
                                @click="showSessionDetailsModal = false">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
    <script>
        let feedback_url = '';

        {% if session['feedback_url'] %}
            feedback_url = {{ session['feedback_url']|tojson }};
            {{ session.pop('feedback_url') }}
        {% endif %}

        if (feedback_url !== '') {
            console.log('feedback_url', feedback_url);
            window.open(feedback_url, '_blank');
        }

        function modals() {
            return {
                showNewNoteModal: false,
                showSessionDetailsModal: false,
                session: {},

                showSessionDetails(session) {
                    this.session = session;
                    this.student = session.student;
                    this.showSessionDetailsModal = true;
                },

                editSession() {
                    window.location.href = `/students/${this.student.id}/sessions/${this.session.id}/edit`
                }
            }
        }

        const sessionsTable = new simpleDatatables.DataTable("#sessions", {
            searchable: true,
            fixedHeight: true,
            columns: [
                {select: 0, sort: 'desc',}
            ],
            perPage: 5,
        });

        const notesTable = new simpleDatatables.DataTable("#notes", {
            searchable: true,
            fixedHeight: true,
            columns: [
                {select: 0, sort: 'desc',}
            ],
            perPage: 5,
        });
    </script>
{% endblock %}