app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from werkzeug.urls import url_parse
from flask_login import login_user, current_user, logout_user, login_required

from app import bcrypt
from app.forms.auth import RegisterForm, LoginForm
from app.models.User import create_user, get_user_by_email

bp = Blueprint("auth", __name__)


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data

        if get_user_by_email(email):
            flash("A user already exists with that email address!")
            return render_template("auth/register.html", form=form), 400

        create_user(name, email, password)

        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("auth.login")

        flash("You have successfully registered. You can now login.")
        return redirect(next_page)

    return render_template("auth/register.html", form=form)


@bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    form = LoginForm()
    if form.validate_on_submit():
        user = get_user_by_email(form.email.data)

        if user is None or not bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            flash("Invalid email address or password")
            return render_template("auth/login.html", title="Sign In", form=form), 401

        login_user(user)
        session["user_name"] = user.name
        session["user_id"] = user.id
        session["is_admin"] = user.is_admin
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("main.dashboard")

        flash("You have been logged in", "success")
        return redirect(next_page)

    return render_template("auth/login.html", form=form)


@bp.route("/logout")
@login_required
def logout():
    if current_user.is_authenticated:
        logout_user()
        flash("You have been logged out")
    return redirect(url_for("auth.login"))

app/routes/reports.py
from datetime import datetime
from math import floor
from decimal import Decimal

from flask import Blueprint, render_template
from flask_login import current_user, login_required

from app.models.Student import (
    get_mentor_sessions_between_dates,
    get_mentor_active_students_by_contact,
)

bp = Blueprint("reports", __name__)


@bp.route("/reports/sessions-report", methods=["GET"])
@login_required
def sessions_report():
    start = datetime.utcnow().replace(day=1, hour=0, minute=0, second=0)
    end = datetime.utcnow()

    sessions = get_mentor_sessions_between_dates(current_user.id, start, end)
    duration_mins = calculate_sessions_duration_min_mins(sessions)
    duration = format_duration_string(duration_mins)
    invoice_amount = Decimal(
        (duration_mins / 60) * (current_user.hourly_rate / 100)
    ).quantize(Decimal(10) ** -2)

    return render_template(
        "reports/sessions.html",
        sessions=sessions,
        duration=duration,
        invoice_amount=invoice_amount,
    )


@bp.route("/reports/student-activity-report", methods=["GET"])
@login_required
def student_activity_report():
    students = get_mentor_active_students_by_contact(current_user.id)

    return render_template("reports/activity_report.html", students=students)


def calculate_sessions_duration_min_mins(sessions):
    duration_mins = 0
    for session in sessions:
        duration_mins += session.duration

    return duration_mins


def format_duration_string(duration_mins):
    hours = floor(duration_mins / 60)
    mins = duration_mins % 60
    mins = mins if len(str(mins)) > 1 else f"0{mins}"

    return f"{hours} Hours and {mins} minutes"

app/routes/students.py
from math import floor

import htmlentities
from flask import Blueprint, flash, redirect, render_template, url_for, abort, session
from flask_login import login_required, current_user

from app.forms.students import (
    AddStudentForm,
    EditStudentForm,
    AddStudentNoteForm,
    AddStudentSessionForm,
)
from app.models.Student import (
    create_student,
    get_mentor_students,
    update_student,
    get_student_by_id,
    add_student_note,
    update_contact_date,
    create_student_session,
    update_student_session,
    get_session_by_id,
)

bp = Blueprint("students", __name__)


@bp.route("/students", methods=["GET"])
@login_required
def index():
    students = get_mentor_students(current_user.id)
    return render_template("students/index.html", students=students)


@bp.route("/students/active", methods=["GET"])
@login_required
def active_students():
    students = get_mentor_students(current_user.id, active_only=True)
    return render_template("students/index.html", students=students)


@bp.route("/students/new", methods=["POST", "GET"])
@login_required
def new():
    form = AddStudentForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        course = form.course.data
        stage = form.course.data

        create_student(name, email, course, stage, current_user.id)

        flash("New student saved")
        return redirect(url_for("students.index"))

    return render_template("students/create.html", form=form)


@bp.route("/students/<student_id>")
@login_required
def view(student_id):
    student = get_student_by_id(student_id)
    add_student_note_form = AddStudentNoteForm()

    if not student:
        return abort(404)

    if current_user.id is not student.mentor_id:
        return abort(404)

    return render_template(
        "students/view.html",
        student=student,
        add_student_note_form=add_student_note_form,
    )


@bp.route("/students/<student_id>/edit", methods=["POST", "GET"])
@login_required
def edit(student_id):
    form = EditStudentForm()
    student = get_student_by_id(student_id)
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        course = form.course.data
        stage = form.stage.data
        active = True if form.active.data == "1" else False

        if not update_student(
            student.id, name, email, course, stage, active, current_user.id
        ):
            return redirect(url_for("students.index")), 403

        flash("Student Successfully Updated")
        return redirect(url_for("students.index"))

    return render_template("students/edit.html", form=form, student=student)


@bp.route("/students/<student_id>/notes", methods=["POST"])
@login_required
def add_note(student_id):
    form = AddStudentNoteForm()
    student = get_student_by_id(student_id)
    if form.validate_on_submit():
        note = form.note.data

        add_student_note(student.id, note)

        if form.update_contact_date.data == "yes":
            update_contact_date(student_id)

        flash("Note successfully saved", "success")
        return redirect(url_for("students.view", student_id=student.id))

    flash(
        "There was a problem adding this note, make sure you actually add a note",
        "error",
    )
    return render_template(
        "students/view.html", student=student, add_student_note_form=form
    )


@bp.route("/students/<student_id>/sessions", methods=["POST", "GET"])
@login_required
def add_session(student_id):
    form = AddStudentSessionForm()
    student = get_student_by_id(student_id)
    if form.validate_on_submit():
        date = form.date.data
        duration = form.duration.data + 4
        session_type = form.session_type.data
        project = form.project.data
        summary = form.summary.data
        progress = form.progress.data
        followup = form.followup.data
        personal_notes = form.personal_notes.data

        student_session = create_student_session(
            student_id,
            date,
            duration,
            session_type,
            project,
            summary,
            progress,
            followup,
            personal_notes,
        )

        if form.send_feedback.data == "yes":
            session["feedback_url"] = generate_feedback_url(
                student, student_session, current_user
            )

        flash("Session successfully saved", "success")
        return redirect(url_for("students.view", student_id=student.id))

    return render_template("students/sessions/create.html", student=student, form=form)


@bp.route("/students/<student_id>/sessions/<session_id>/edit", methods=["GET", "POST"])
@login_required
def update_session(student_id, session_id):
    form = AddStudentSessionForm()
    student = get_student_by_id(student_id)
    session = get_session_by_id(session_id)
    if form.validate_on_submit():
        date = form.date.data
        duration = form.duration.data
        session_type = form.session_type.data
        project = form.project.data
        summary = form.summary.data
        progress = form.progress.data
        followup = form.followup.data
        personal_notes = form.personal_notes.data

        update_student_session(
            student_id,
            session_id,
            date,
            duration,
            session_type,
            project,
            summary,
            progress,
            followup,
            personal_notes,
        )

        flash("Session successfully updated", "success")
        return redirect(url_for("students.view", student_id=student_id))

    return render_template(
        "students/sessions/edit.html", student=student, form=form, session=session
    )


def generate_feedback_url(student, student_session, mentor):
    """
    Generates URL to autofill CI session feedback
    :param student:
    :param student_session:
    :param mentor:
    :return: string
    """
    types = {
        "select": "Please Select",
        "intro": "Intro",
        "inception": "Project inception",
        "middle": "Middle of project",
        "end": "End of project",
        "prep": "Interview preparation and career advice",
        "no-show-valid": "Postponed (Valid Reason)",
        "no-show": "**No-show**",
        "other": "Other",
    }

    projects = {
        "intro": "Intro/Interview",
        "UCFD": "User Centric Front End Development (MS1)",
        "IFD": "Interactive Front End Development (MS2)",
        "DCD": "Data Centric Development (MS3)",
        "FSFwD": "Full Stack Frameworks with Django (MS4)",
        "PP1": "HTML/CSS Essentials (PP1)",
        "PP2": "JavaScript Essentials (PP2)",
        "PP3": "Python Essentials (PP3)",
        "PP4": "Full Stack Toolkit (PP4)",
        "PP5": "eCommerce (PP5)",
    }

    progress = {
        "poor": "I'm worried about this student's progress.",
        "average": "Average - The student is moving at an acceptable pace.",
        "excellent": "Excellent - It's going great.",
    }
    followup = {
        "Yes": "Yes",
        "No": "No",
    }
    firstsubmission = {
        "Yes": "First Time Submission",
        "No": "Project Resubmission"
    }

    hours = floor(student_session.duration / 60)
    mins = str(student_session.duration  % 60)
    mins = mins if len(mins) > 1 else f"0{mins}"
    duration = f"0{hours}:{mins}:00"

    feedbackurl = "https://docs.google.com/forms/d/e/1FAIpQLSfUCSyObKZDjjtAhIgc8r5FrA4VSUflq1dMK6QyYMv33LeEDQ/viewform?c=0&w=1"
    feedbackurl += f"&emailAddress={htmlentities.encode(mentor.email)}"
    feedbackurl += f"&entry.1191000917={htmlentities.encode(student_session.date.strftime('%Y-%m-%d'))}"
    feedbackurl += f"&entry.1269347964={htmlentities.encode(student.email)}"
    feedbackurl += (
        f"&entry.1521715512={htmlentities.encode(types[student_session.session_type])}"
    )
    feedbackurl += (
        f"&entry.478142644={htmlentities.encode(projects[student_session.project])}"
    )
    feedbackurl += f"&entry.775489883={htmlentities.encode(duration)}"
    feedbackurl += (
        f"&entry.2010663110={htmlentities.encode(progress[student_session.progress])}"
    )
    feedbackurl += f"&entry.1882714143={htmlentities.encode(student_session.summary)}"
    feedbackurl += f"&entry.1360996801={htmlentities.encode(student_session.followup)}"
    feedbackurl += "&entry.1121396892=First Time Submission"
    feedbackurl += "&emailReceipt=true"

    return feedbackurl.replace("\r", " ").replace("\n", "")

app/templates/dashboard.html
{% extends 'layouts/app.html' %}

{% block app_content %}
    <div class="bg-indigo-600 p-2 shadow text-xl text-white flex justify-between">
        <h3 class="font-bold pl-2 inline">Dashboard</h3>
    </div>
    <div class="flex flex-wrap">
        <div class="w-full md:w-1/2 xl:w-1/3 p-3 pl-0">
            <div class="bg-blue-100 border-b-4 border-blue-500 shadow-lg p-5">
                <div class="flex flex-row items-center">
                    <div class="flex-shrink pr-4">
                        <a href="{{ url_for('students.index') }}">
                            <div class="rounded-full p-5 bg-blue-600">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                                </svg>
                            </div>
                        </a>
                    </div>
                    <div class="flex-1 text-right md:text-center">
                        <a href="{{ url_for('students.index') }}">
                            <h5 class="font-bold uppercase text-gray-600">Total Students</h5>
                            <h3 class="font-bold text-3xl">{{ total_students|length }}</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/2 xl:w-1/3 p-3">
            <div class="bg-green-100 border-b-4 border-green-500 shadow-lg p-5">
                <div class="flex flex-row items-center">
                    <div class="flex-shrink pr-4">
                        <div class="rounded-full p-5 bg-green-600">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                      d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="flex-1 text-right md:text-center">
                        <a href="{{ url_for('students.active_students') }}">
                            <h5 class="font-bold uppercase text-gray-600">Active Students</h5>
                            <h3 class="font-bold text-3xl">{{ active_students|length }}</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/2 xl:w-1/3 p-3 pr-0">
            <div class="bg-yellow-100 border-b-4 border-yellow-500 shadow-lg p-5">
                <div class="flex flex-row items-center">
                    <div class="flex-shrink pr-4">
                        <a href="#">
                            <div class="rounded-full p-5 bg-yellow-600">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M4 6h16M4 10h16M4 14h16M4 18h16"></path>
                                </svg>
                            </div>
                        </a>
                    </div>
                    <div class="flex-1 text-right md:text-center">
                        <a href="{{ url_for("reports.sessions_report") }}">
                            <h5 class="font-bold uppercase text-gray-600">Sessions This Month</h5>
                            <h3 class="font-bold text-3xl">{{ month_sessions|length }}</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MentorDashboard</title>

    <!-- Styles -->
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 h-screen antialiased leading-none">
<div class="flex flex-col">
    <div class="min-h-screen flex items-center justify-center">
        <div class="flex flex-col justify-around h-full">
            <div>
                <h1 class="text-gray-600 text-center font-light tracking-wider text-5xl mb-6">
                    MentorDashboard
                </h1>
                <h2 class="text-gray-600 text-center font-light tracking-wider text-4xl mb-6">
                    New dashboard for Code Institute Mentors, <br/>coming soon!
                </h2>
                <h3 class="text-gray-600 text-center font-light tracking-wider text-xl mb-6">
                    <a href="{{ url_for('auth.register') }}">Register a new account</a> OR <a
                        href="{{ url_for('auth.login') }}">Login Here</a>
                </h3>
            </div>
        </div>
    </div>
</div>
</body>
</html>